############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Features"
url = "/features"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Elements"
url = "/elements"
weight = 4

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
