############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Features"
url = "/features"
weight = 3

[[main]]
name = "Documentation"
weight = 4

[[main]]
parent = "Documentation"
name = "Getting Started"
url = "/getting-started"
weight = 1

[[main]]
parent = "Documentation"
name = "API Docs"
url = "/api-documentation"
weight = 2
 

[[main]]
name = "Contact"
url = "/contact"
weight = 5

[[footer]]
name = "Elements"
url = "/elements"
weight = 4

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
